/* tslint:disable */
/* eslint-disable */
/**
 * IONOS DBaaS MongoDB REST API
 * With IONOS Cloud Database as a Service, you have the ability to quickly set up and manage a MongoDB database. You can also delete clusters, manage backups and users via the API.  MongoDB is an open source, cross-platform, document-oriented database program. Classified as a NoSQL database program, it uses JSON-like documents with optional schemas.  The MongoDB API allows you to create additional database clusters or modify existing ones. Both tools, the Data Center Designer (DCD) and the API use the same concepts consistently and are well suited for smooth and intuitive use. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Connection } from './connection';
import { MaintenanceWindow } from './maintenance-window';

/**
 * The properties with all data needed to create a new MongoDB cluster. 
 * @export
 * @interface CreateClusterProperties
 */
export interface CreateClusterProperties {

    /**
     * The unique ID of the template, which specifies the number of cores, storage size, and memory. You cannot downgrade to a smaller template or minor edition (e.g. from business to playground). To get a list of all templates to confirm the changes use the /templates endpoint. 
     * @type {string}
     * @memberof CreateClusterProperties
     */
    templateID: string;

    /**
     * The MongoDB version of your cluster.
     * @type {string}
     * @memberof CreateClusterProperties
     */
    mongoDBVersion?: string;

    /**
     * The total number of instances in the cluster (one primary and n-1 secondaries). 
     * @type {number}
     * @memberof CreateClusterProperties
     */
    instances: number;

    /**
     * 
     * @type {Array<Connection>}
     * @memberof CreateClusterProperties
     */
    connections: Array<Connection>;

    /**
     * The physical location where the cluster will be created. This is the location where all your instances will be located. This property is immutable. 
     * @type {string}
     * @memberof CreateClusterProperties
     */
    location: string;

    /**
     * The name of your cluster.
     * @type {string}
     * @memberof CreateClusterProperties
     */
    displayName: string;

    /**
     * 
     * @type {MaintenanceWindow}
     * @memberof CreateClusterProperties
     */
    maintenanceWindow?: MaintenanceWindow;
}


