/* tslint:disable */
/* eslint-disable */
/**
 * IONOS DBaaS MongoDB REST API
 * With IONOS Cloud Database as a Service, you have the ability to quickly set up and manage a MongoDB database. You can also delete clusters, manage backups and users via the API.  MongoDB is an open source, cross-platform, document-oriented database program. Classified as a NoSQL database program, it uses JSON-like documents with optional schemas.  The MongoDB API allows you to create additional database clusters or modify existing ones. Both tools, the Data Center Designer (DCD) and the API use the same concepts consistently and are well suited for smooth and intuitive use. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A MongoDB template item.
 * @export
 * @interface TemplateResponse
 */
export interface TemplateResponse {

    /**
     * The unique template ID.
     * @type {string}
     * @memberof TemplateResponse
     */
    id?: string;

    /**
     * The name of the template.
     * @type {string}
     * @memberof TemplateResponse
     */
    name?: string;

    /**
     * The edition of the template (e.g. enterprise)
     * @type {string}
     * @memberof TemplateResponse
     */
    edition?: string;

    /**
     * The number of CPU cores.
     * @type {number}
     * @memberof TemplateResponse
     */
    cores?: number;

    /**
     * The amount of memory in GB.
     * @type {number}
     * @memberof TemplateResponse
     */
    ram?: number;

    /**
     * The amount of storage size in GB.
     * @type {number}
     * @memberof TemplateResponse
     */
    storageSize?: number;
}


